dist: focal
language: cpp

services:
- docker

before_install:
- docker build -t hbgit/map2checklibrary --no-cache -f Dockerfile .
- sudo apt install -y python3-pip
- pip3 install --user cpp-coveralls  

script:
- docker run --rm -v $(pwd):/home/:Z --user $(id -u):$(id -g) hbgit/map2checklibrary /bin/bash -c "cd home/; ./build.sh -d"

after_success:
- ls -alh
- bash <(curl -s https://codecov.io/bash) -f build/test/lcov.info || echo "Codecov did not collect coverage reports"
- cat build/test/lcov.info | coveralls -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --exclude header_old --exclude lib_old --exclude docs --exclude build --exclude release-library

notifications:
  email: false