dist: focal
language: cpp

services:
- docker

before_install:
- docker build -t hbgit/map2checklibrary --no-cache -f Dockerfile .
- sudo apt install -y python3-pip
- pip3 install --user cpp-coveralls  

script:
- docker run --rm -v $(pwd):/home/:Z --user $(id -u):$(id -g) hbgit/map2checklibrary /bin/bash -c "cd home/; mkdir build; cd build; cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_INSTALL_PREFIX=../release-library/ -DENABLE_TEST=ON -DENABLE_COVCODE=ON; make; ./test/unit_tests"

after_success:
- ls -alh
- coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false