/* SPDX-License-Identifier: GPL-3.0-only
 *
 * Stress harness for the map2check-library FFI boundary (M2 acceptance
 * criterion): every symbol exported by `rust/src/ffi.rs` and
 * `rust/src/nondet/libfuzzer.rs` must be reachable from C, survive hostile
 * inputs (null pointers, non-UTF8/garbage strings, pre-init calls) and run
 * clean under ASan+UBSan (no abort, no UB).
 *
 * `map2check.h` (generated by cbindgen) does not cover the macro-generated
 * exports (nondet log savers and most overflow binops), because cbindgen
 * does not expand `macro_rules!`. Those are declared by hand below with the
 * exact signatures from `ffi.rs`.
 */
#include <stdint.h>
#include <stddef.h>

#include "../include/map2check.h"

/* ── Manual declarations for macro-generated exports absent from the
 *    cbindgen header (see rust/src/ffi.rs: nondet_ffi!, overflow_ffi_binop!,
 *    overflow_ffi_shift!) ────────────────────────────────────────────── */

extern void map2check_save_nondet_log_int(int32_t line, int32_t scope, int32_t value, const char *function_name);
extern void map2check_save_nondet_log_uint(int32_t line, int32_t scope, uint32_t value, const char *function_name);
extern void map2check_save_nondet_log_long(int32_t line, int32_t scope, int64_t value, const char *function_name);
extern void map2check_save_nondet_log_char(int32_t line, int32_t scope, int8_t value, const char *function_name);
extern void map2check_save_nondet_log_float(int32_t line, int32_t scope, float value, const char *function_name);
extern void map2check_save_nondet_log_double(int32_t line, int32_t scope, double value, const char *function_name);

extern void map2check_binop_add_int(int32_t param1, int32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_sub_int(int32_t param1, int32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_mul_int(int32_t param1, int32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_div_int(int32_t param1, int32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_add_unsigned(uint32_t param1, uint32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_sub_unsigned(uint32_t param1, uint32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_mul_unsigned(uint32_t param1, uint32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_div_unsigned(uint32_t param1, uint32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_shl_int(int32_t param1, uint32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_shr_int(int32_t param1, uint32_t param2, uint32_t line, uint32_t scope, const char *function_name);
extern void map2check_binop_shr_unsigned(uint32_t param1, uint32_t param2, uint32_t line, uint32_t scope, const char *function_name);

/* Test-only entry point LibFuzzer's LLVMFuzzerTestOneInput calls into
 * (rust/src/nondet/libfuzzer.rs only defines this under cfg(test); the real
 * static lib expects the linking program — here, this harness — to provide
 * it). */
int __map2check_main__(void) {
    return 0;
}

/* ── Round 1: hostile calls made *before* map2check_init() ──────────────
 * Exercises null pointers, empty/garbage strings and pre-init access for
 * every export that can plausibly be called out of order.
 */
static void run_bad_inputs(void) {
    /* result/state management, pre-init */
    map2check_reset();
    set_false_result(MemsafetyDeref, -1, NULL);
    (void)get_current_property();
    (void)get_current_step();
    (void)get_next_step();
    print_all_containers_as_json();
    vcc_reset_meta_data();
    map2check_set_memcleanup();
    map2check_set_null_is_valid();

    /* memory/deref/free/load checks, pre-init */
    map2check_check_load(NULL, 1, 0, 8, NULL);
    map2check_check_deref(NULL, 0, 2, NULL);
    map2check_check_free(NULL, NULL, 0, 3, NULL);
    map2check_check_free_resolved_address(NULL, 3, NULL);
    map2check_check_mem_endprog();

    /* memtrack with null/empty strings */
    map2check_map_alloca(NULL, NULL, 4, 4, 4, 1);
    map2check_map_alloca("", NULL, 4, 4, 5, 1);
    map2check_map_non_static_alloca(NULL, NULL, 4, 4, 4, 1);
    map2check_map_non_static_alloca("", NULL, 4, 4, 5, 1);
    map2check_map_funct_address(NULL, NULL, 4, 1);
    map2check_map_funct_address("", NULL, 5, 1);
    map2check_map_malloc(NULL, -1);
    map2check_map_calloc(NULL, -1, -1);
    map2check_map_store_pointer(NULL, NULL, 0, NULL, 6, NULL);
    map2check_map_free(NULL, NULL, 0, 7, NULL);

    /* basic-block tracking, pre-init */
    map2check_save_basic_block_log(8, NULL);
    (void)map2check_is_in_trackbb_container(-1);

    /* nondet log savers with null function name */
    map2check_save_nondet_log_int(9, 0, -1, NULL);
    map2check_save_nondet_log_uint(9, 0, 0, NULL);
    map2check_save_nondet_log_long(9, 0, -1, NULL);
    map2check_save_nondet_log_char(9, 0, 0, NULL);
    map2check_save_nondet_log_float(9, 0, 0.0f, NULL);
    map2check_save_nondet_log_double(9, 0, 0.0, NULL);

    /* assert and overflow family with null function name / extreme values */
    map2check_is_valid_assert(10, NULL, 0);
    map2check_binop_add_int(2147483647, 1, 10, 0, NULL);
    map2check_binop_sub_int(-2147483648, 1, 10, 0, NULL);
    map2check_binop_mul_int(2147483647, 2, 10, 0, NULL);
    map2check_binop_div_int(1, 0, 10, 0, NULL);
    map2check_binop_add_unsigned(4294967295u, 1, 10, 0, NULL);
    map2check_binop_sub_unsigned(0, 1, 10, 0, NULL);
    map2check_binop_mul_unsigned(4294967295u, 2, 10, 0, NULL);
    map2check_binop_div_unsigned(1, 0, 10, 0, NULL);
    map2check_binop_neg_int(-2147483648, 11, 0, NULL);
    map2check_binop_shl_int(1, 31, 11, 0, NULL);
    map2check_binop_shr_int(-1, 32, 11, 0, NULL);
    map2check_binop_shr_unsigned(4294967295u, 32, 11, 0, NULL);

    /* nondet generators, pre-init */
    (void)__VERIFIER_nondet_bool();
    (void)__VERIFIER_nondet_char();
    (void)__VERIFIER_nondet_uchar();
    (void)__VERIFIER_nondet_short();
    (void)__VERIFIER_nondet_ushort();
    (void)__VERIFIER_nondet_int();
    (void)__VERIFIER_nondet_uint();
    (void)__VERIFIER_nondet_long();
    (void)__VERIFIER_nondet_ulong();
    (void)__VERIFIER_nondet_float();
    (void)__VERIFIER_nondet_double();
    (void)__VERIFIER_nondet_size_t();
    (void)__VERIFIER_nondet_pointer();

    /* __VERIFIER_assume/assert/map2check_fuzzer_assume only with a truthy
     * condition here: a falsy one calls exit(0)/abort() by design (see
     * rust/src/nondet/libfuzzer.rs), which would end this harness process
     * instead of just this check. */
    __VERIFIER_assume(1);
    __VERIFIER_assert(1);
    map2check_fuzzer_assume(1);
}

/* ── Round 2: a well-formed pass after init(), touching every export with
 * sane arguments (belt-and-suspenders alongside the hostile round above so
 * every symbol is proven reachable, not just tolerant of garbage). ────── */
static void run_valid_pass(void) {
    map2check_map_malloc(NULL, 16);
    map2check_map_calloc(NULL, 4, 8);
    map2check_map_alloca("buf", NULL, 8, 8, 20, 1);
    map2check_map_non_static_alloca("vla", (void *)0x3, 8, 8, 20, 1);
    map2check_map_funct_address("f", (void *)0x4, 20, 1);
    map2check_map_store_pointer((void *)0x1, (void *)0x2, 1, "buf", 21, "main");
    map2check_map_free("buf", (void *)0x1, 1, 22, "main");

    map2check_check_load((void *)0x1, 23, 1, 4, "main");
    map2check_check_deref((void *)0x1, 1, 24, "main");
    map2check_check_free("buf", (void *)0x1, 1, 25, "main");
    map2check_check_free_resolved_address((void *)0x2, 25, "main");
    map2check_check_mem_endprog();

    map2check_save_basic_block_log(26, "main");
    (void)map2check_is_in_trackbb_container(26);

    map2check_save_nondet_log_int(27, 0, 42, "main");
    map2check_save_nondet_log_uint(27, 0, 42u, "main");
    map2check_save_nondet_log_long(27, 0, 42, "main");
    map2check_save_nondet_log_char(27, 0, 'a', "main");
    map2check_save_nondet_log_float(27, 0, 1.5f, "main");
    map2check_save_nondet_log_double(27, 0, 1.5, "main");

    map2check_is_valid_assert(28, "main", 1);
    map2check_binop_add_int(1, 2, 29, 0, "main");
    map2check_binop_sub_int(2, 1, 29, 0, "main");
    map2check_binop_mul_int(2, 3, 29, 0, "main");
    map2check_binop_div_int(6, 3, 29, 0, "main");
    map2check_binop_add_unsigned(1u, 2u, 29, 0, "main");
    map2check_binop_sub_unsigned(2u, 1u, 29, 0, "main");
    map2check_binop_mul_unsigned(2u, 3u, 29, 0, "main");
    map2check_binop_div_unsigned(6u, 3u, 29, 0, "main");
    map2check_binop_neg_int(5, 29, 0, "main");
    map2check_binop_shl_int(1, 2, 29, 0, "main");
    map2check_binop_shr_int(8, 2, 29, 0, "main");
    map2check_binop_shr_unsigned(8u, 2u, 29, 0, "main");

    (void)__VERIFIER_nondet_bool();
    (void)__VERIFIER_nondet_char();
    (void)__VERIFIER_nondet_uchar();
    (void)__VERIFIER_nondet_short();
    (void)__VERIFIER_nondet_ushort();
    (void)__VERIFIER_nondet_int();
    (void)__VERIFIER_nondet_uint();
    (void)__VERIFIER_nondet_long();
    (void)__VERIFIER_nondet_ulong();
    (void)__VERIFIER_nondet_float();
    (void)__VERIFIER_nondet_double();
    (void)__VERIFIER_nondet_size_t();
    (void)__VERIFIER_nondet_pointer();
    __VERIFIER_assume(1);
    __VERIFIER_assert(1);
    map2check_fuzzer_assume(1);

    set_false_result(MemsafetyMemtrack, 30, "main");
    (void)get_current_property();
    (void)get_current_step();
    (void)get_next_step();
    vcc_reset_meta_data();
    map2check_set_memcleanup();
    map2check_set_null_is_valid();
    map2check_check_mem_endprog();
    print_all_containers_as_json();
}

int main(void) {
    /* round 1: adversarial inputs before init */
    run_bad_inputs();

    /* round 2: well-formed use of every export after init */
    map2check_init();
    run_valid_pass();

    /* explicit reset between "runs" */
    map2check_reset();

    /* round 3: adversarial inputs again, post-reset */
    run_bad_inputs();

    /* two consecutive LibFuzzer iterations must start from independent
     * state (see rust/src/nondet/libfuzzer.rs: state::reset() per call). */
    {
        const uint8_t first_input[] = {0x01, 0x02, 0x03, 0x04};
        const uint8_t second_input[] = {0xa0, 0xb0};
        if (LLVMFuzzerTestOneInput(first_input, sizeof(first_input)) != 0 ||
            LLVMFuzzerTestOneInput(second_input, sizeof(second_input)) != 0) {
            return 1;
        }
    }

    map2check_success();
    return 0;
}
